[package]
name = "rusty-space"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
glam = "0.25.0"
num-traits = "0.2.17"
bevy = "0.13.0"
once_cell = "1.19.0"
image = "0.25.0"
winit = "0.29.15"
